Fixed url creating for feach features
growthbook/growthbook-kotlin pull request #11
Opened 2022-03-25 14:14 UTC by VovaStelmashchuk

- Fixed url creating, now url creating in case when host doesn't have dash.
- Add contributing guide line.

Simplified version of #10

2022-03-25 14:25 UTC, VovaStelmashchuk commented
Fixes for cases when a developer provide a host with slash or without slash. Each case are correct, but library create incorrect request the host in case when url without slash.

2022-03-25 15:11 UTC, VovaStelmashchuk commented
@stevenleadbeater Can you check error into `Test coverage`. I see some package cannot install, may be needs some changes into action source.

2022-03-26 12:20 UTC, stevenleadbeater commented
@VovaStelmashchuk let me take a look at that for you

2022-03-28 07:50 UTC, VovaStelmashchuk commented
A problem is a pipeline tries to install a package. I think it is a wrong way for CI. The pipeline  has depends on ubuntu package storage. 

My proposal don't use bash/shell executor into CI instead create Docker image with all tools which you need to the pipeline 
job. 
[Creating a Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)

Pluses:
- CI runs faster  
- No depends
- Developers can use the docker image for run ci jobs localy.

[Link to CI template how uses shell](https://github.com/stevenleadbeater/kotlin-kover-action/blob/main/action.yml)

2022-03-28 08:15 UTC, stevenleadbeater commented
Yes you're right there. I've done docker containers for actions before. I'll refactor this one to use that style too. I had used the composite action instead originally as it's simpler to setup and less moving parts. I've got a docker quay account anyway so there's no problems converting it. Give me a bit and I'll fix it up this morning UST time 😉

2022-03-28 10:09 UTC, stevenleadbeater commented
All fixed @VovaStelmashchuk , please push a whitespace change to ensure the builds run using the latest versions of the actions involved

2022-03-29 09:59 UTC, stevenleadbeater commented
looking at this now, please stand by

2022-03-29 10:05 UTC, stevenleadbeater requested changes

2022-03-29 10:05 UTC, stevenleadbeater commented on .github/workflows/pull-request.yml
> +        proxy-url: https://add-pr-comment-proxy-94idvmwyie-uc.a.run.app
There are warnings about this in the workflow output. Can you remove it please?

2022-03-29 10:06 UTC, stevenleadbeater commented
> Ok, my suggest [stevenleadbeater/kotlin-kover-action#1](https://github.com/stevenleadbeater/kotlin-kover-action/pull/1)
> 
> I am not sure about solution at the moment :)

I had some similar issues going on on my Fork. It may be using an older version of the action. I resolved it by closing the pull request and opening a new one

2022-03-29 10:06 UTC, stevenleadbeater commented
Run mshick/add-pr-comment@v1
  with:
    message: | Area  | Coverage(%) | Status |
  | ------------- | ------------- | ------------- |
  | **Line**  | 94  | :heavy_check_mark: |
  | **Instruction**  | 85  | :heavy_check_mark:  |
  | **Branch**  | 66  | :x:  |
  | **Method**  | 88  | :heavy_check_mark:  |
  | **Class**  | 89  | :heavy_check_mark:  |
  
    repo-token: ***
    repo-token-user-login: github-actions[bot]
    allow-repeats: false
  env:
    JAVA_HOME_11.0.14_x64: /opt/hostedtoolcache/jdk/11.0.14/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.14/x64
    JAVA_HOME_11_0_14_X64: /opt/hostedtoolcache/jdk/11.0.14/x64
Error: Resource not accessible by integration

2022-03-29 10:08 UTC, stevenleadbeater commented
Found you:
Proxy for Fork-based PRs

GitHub limits GITHUB_TOKEN and other API access token permissions when creating a PR from a fork. This precludes adding comments when your PRs are coming from forks, which is the norm for open source projects. To work around this situation I've created a simple companion app you can deploy to Cloud Run or another host to proxy the create comment requests with a personal access token you provide.

2022-03-29 10:09 UTC, stevenleadbeater commented
this needs adding in to the composite action. Please stand by while I test a fix :)

2022-03-29 10:23 UTC, stevenleadbeater commented
Please add the:
        `proxy-url: https://add-pr-comment-proxy-94idvmwyie-uc.a.run.app`
back in, it is now supported in the action and should resolve the build failure

2022-03-29 10:52 UTC, stevenleadbeater commented
This is missing the comments on coverage, that's a pain. It looks like it's related to tokens not being accessible to PRs from forks. It's a security risk as anyone can open a fork, if they then modify the workflow they can potentially exfiltrate the token and do all sorts of nasty things. I'm going to spend a bit of time on this and see what's possible. there's the proxy with access to write comments that you found but that requires an instance running in google cloud and seems prone to breaking and failure. I'll keep looking at this. I would like to find a solution that doesn't require proxies or manual steps and retains the security of the repository

2022-03-29 12:01 UTC, stevenleadbeater commented
Looks like codecov is the way to go for this. I'll get everything updated and integrate it back in. For now, your coverage is:
  | message: | Area  | Coverage(%) | Status |
  | ------------- | ------------- | ------------- |
  | **Line**  | 94  | :heavy_check_mark: |
  | **Instruction**  | 85  | :heavy_check_mark:  |
  | **Branch**  | 66  | :x:  |
  | **Method**  | 88  | :heavy_check_mark:  |
  | **Class**  | 90  | :heavy_check_mark:  |

2022-03-29 12:33 UTC, VovaStelmashchuk commented
Ok. Do i need to add new tests for increase branch test coverage

You can have my help with codecov if your want to.

2022-03-31 18:26 UTC, stevenleadbeater commented
Sorry @VovaStelmashchuk I missed that comment. No it's a pre-existing issue. The branch coverage is for the repository as a whole. I'll alter that action to allow different limits for the different areas. That way it can be lowered for branch so we can ensure future work doesn't reduce coverage further but not flag new work as causing a pre-existing issue

2022-04-01 08:32 UTC, VovaStelmashchuk commented
Ок.
@jdorn Can we merge the PR ?

2022-04-07 19:31 UTC, merged